
config:
  MD013: false

  MD033: false

  MD034: false

  MD041: false

  MD003: false

  MD012:
    maximum: 2

  MD060: false

  MD040: false

  MD024:
    siblings_only: true

globs:
  - "docs/**/*.md"
  - "*.md"
ignores:
  - "node_modules/**"
  - "web/**"
  - "**/CHANGELOG.md"
