source "https://rubygems.org"

gem "rails", "~> 8.0"
gem "puma", "~> 6.5"
gem "pg", "~> 1.5"
gem "redis", "~> 5.3"
gem "sidekiq", "~> 7.3"
gem "devise", "~> 4.9"
gem "pundit", "~> 2.4"
gem "rack-cors", "~> 2.0"
gem "jbuilder", "~> 2.13"
gem "bootsnap", "~> 1.18"
gem "sprockets-rails", "~> 3.5"
gem "importmap-rails", "~> 2.1"
gem "turbo-rails", "~> 2.0"
gem "stimulus-rails", "~> 1.3"

group :development, :test do
  gem "rspec-rails", "~> 7.1"
  gem "factory_bot_rails", "~> 6.4"
  gem "faker", "~> 3.5"
  gem "rubocop", "~> 1.69"
  gem "rubocop-rails", "~> 2.27"
end
