apiVersion: v1
kind: Service
metadata:
  name: {{ include "sparkwing-full.controller.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sparkwing-full.componentLabels" (dict "root" . "component" "controller") | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "sparkwing-full.componentSelectorLabels" (dict "root" . "component" "controller") | nindent 4 }}
  ports:
    - name: http
      port: 80
      targetPort: {{ .Values.controller.port }}
