{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "sparkwing-runner-bundle.runner.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sparkwing-runner-bundle.labels" . | nindent 4 }}
rules: []
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "sparkwing-runner-bundle.runner.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sparkwing-runner-bundle.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "sparkwing-runner-bundle.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "sparkwing-runner-bundle.runner.fullname" . }}
{{- end }}
