{{- if .Values.resourceQuota.enabled -}}
apiVersion: v1
kind: ResourceQuota
metadata:
  name: {{ include "sparkwing-runner-bundle.componentFullname" (dict "root" . "component" "quota") }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sparkwing-runner-bundle.labels" . | nindent 4 }}
spec:
  hard:
    {{- toYaml .Values.resourceQuota.hard | nindent 4 }}
{{- end }}
