pipelines:
  - name: pre-commit
    entrypoint: PreCommit

  - name: pre-push
    entrypoint: PrePush

  - name: push-checks
    entrypoint: PrePush

  - name: lint
    entrypoint: Lint

  - name: test
    entrypoint: Test

  - name: static-analysis
    entrypoint: StaticAnalysis

  - name: security-scan
    entrypoint: SecurityScan

  - name: integration
    entrypoint: Integration

  - name: store-postgres
    entrypoint: StorePostgres

  - name: build
    entrypoint: Build

  - name: build-images
    entrypoint: BuildImages

  - name: k8s-e2e
    entrypoint: KubernetesE2E

  - name: release
    entrypoint: Release

  - name: template-verify
    entrypoint: TemplateVerify

  - name: example
    entrypoint: Example

  - name: weather-report
    entrypoint: WeatherReport
